- type: department
  parent: CMDepartmentBase
  id: CMSunRiders
  name: department-CMsunriders
  description: cm-department-sun-riders
  color: "#DE3A3A"
  roles:
  - CMRiflemanPVE
  - CMHospitalCorpsmanPVE
  - CMSmartGunOperatorPVE
  - CMSquadLeaderPVE
  - CMSectionSergeantPVE
  - CMPlatoonCommanderPVE
  departmentRadio: null
  headOfDepartment: CMPlatoonCommanderPVE
