- type: department
  parent: CMDepartmentBase
  id: CMSunRiders
  name: department-CMsunriders
  description: cm-department-sun-riders
  color: "#4148C8"
  roles:
  - CMRiflemanPVE
  - CMHospitalCorpsmanPVE
  - CMSmartGunOperatorPVE
  - CMSquadLeaderPVE
  - CMSectionSergeantPVE
  - CMPlatoonCommanderPVE
  departmentRadio: CMSunRiders
  headOfDepartment: CMPlatoonCommanderPVE
