using Content.Shared._RNMC14.AdminLighting;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map.Components;
using Robust.Shared.Maths;

namespace Content.Client._RNMC14.RNMCLightingTab
{
    [GenerateTypedNameReferences]
    public sealed partial class RNMCLightingWindow : DefaultWindow
    {
        public System.Action<int, string, bool, float>? OnStepExecuted;
        public System.Action<int, string, bool, float>? OnValueModified;
        public System.Action? OnResetRequested;
        public System.Action? OnCancelRequested;

        private readonly string[] _runtimeHexValues = new string[10];
        private readonly LineEdit[] _hexInputs = new LineEdit[10];
        private readonly PanelContainer[] _colorSquares = new PanelContainer[10];
        private bool _isUpdatingState = false;

        public RNMCLightingWindow()
        {
            RobustXamlLoader.Load(this);
            BuildControlGrid();
        }

        private void BuildControlGrid()
        {
            for (int i = 0; i < 10; i++)
            {
                int index = i;
                string localizedName = Loc.GetString($"rnmc-light-step-{i}");

                var lightButton = new Button
                {
                    HorizontalExpand = true,
                    MinHeight = 32,
                    Margin = new Thickness(4, 2)
                };
                var label = new Label
                {
                    Text = $"Set: {localizedName}",
                    HorizontalAlignment = Control.HAlignment.Center,
                    VerticalAlignment = Control.VAlignment.Center
                };
                lightButton.AddChild(label);

                _hexInputs[i] = new LineEdit { MinWidth = 120, Margin = new Thickness(4, 2), HorizontalExpand = false };
                _colorSquares[i] = new PanelContainer { MinWidth = 32, MinHeight = 32, Margin = new Thickness(4, 2), HorizontalExpand = false };

                _hexInputs[i].OnTextChanged += args =>
                {
                    if (_isUpdatingState) return;

                    string text = args.Text.Trim();

                    if (text.Length < 7) return;
                    if (!text.StartsWith("#")) text = "#" + text;

                    try
                    {
                        var parsedColor = Color.FromHex(text);

                        if (parsedColor != Color.Transparent || text == "#00000000" || text == "#000000")
                        {
                            _runtimeHexValues[index] = text;
                            _colorSquares[index].PanelOverride = new StyleBoxFlat { BackgroundColor = parsedColor };
                            TriggerUiStateUpdate(index, text);
                        }
                    }
                    catch
                    {
                    }
                };

                lightButton.OnPressed += _ =>
                {
                    if (!float.TryParse(FadeDurationInput.Text, out var duration)) duration = 5.0f;
                    OnStepExecuted?.Invoke(index, _hexInputs[index].Text, FadeCheckBox.Pressed, duration);
                };

                LightingGridContainer.AddChild(lightButton);
                LightingGridContainer.AddChild(_hexInputs[i]);
                LightingGridContainer.AddChild(_colorSquares[i]);
            }

            FadeCheckBox.OnToggled += _ => TriggerUiStateUpdate(0, "#F6CDB4FF");
            FadeDurationInput.OnTextChanged += _ => TriggerUiStateUpdate(0, "#F6CDB4FF");

            ResetButton.OnPressed += _ => OnResetRequested?.Invoke();
            CancelFadeButton.OnPressed += _ => OnCancelRequested?.Invoke();

            CurrentLightColorBanner.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.Black };
        }

        private void TriggerUiStateUpdate(int index, string activeHex)
        {
            if (_isUpdatingState) return;
            if (!float.TryParse(FadeDurationInput.Text, out var duration)) duration = 5.0f;
            OnValueModified?.Invoke(index, activeHex, FadeCheckBox.Pressed, duration);
        }

        public void UpdateState(AdminLightingEuiState state)
        {
            _isUpdatingState = true;

            FadeCheckBox.Pressed = state.ShouldFade;
            FadeDurationInput.Text = state.FadeDuration.ToString("F1");

            for (int i = 0; i < 10; i++)
            {
                if (i >= state.HexValues.Length) break;

                _runtimeHexValues[i] = state.HexValues[i];
                _hexInputs[i].Text = state.HexValues[i];

                var parsedColor = Color.FromHex(state.HexValues[i]);
                _colorSquares[i].PanelOverride = new StyleBoxFlat { BackgroundColor = parsedColor };
            }

            _isUpdatingState = false;
        }

        protected override void FrameUpdate(Robust.Shared.Timing.FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var entManager = Robust.Shared.IoC.IoCManager.Resolve<IEntityManager>();
            var playerManager = Robust.Shared.IoC.IoCManager.Resolve<Robust.Client.Player.IPlayerManager>();

            if (playerManager.LocalPlayer?.ControlledEntity is not { } playerEntity)
                return;

            if (!entManager.TryGetComponent<TransformComponent>(playerEntity, out var xform))
                return;

            var mapManager = Robust.Shared.IoC.IoCManager.Resolve<Robust.Shared.Map.IMapManager>();
            var mapUid = mapManager.GetMapEntityId(xform.MapID);

            if (!mapUid.IsValid())
                return;

            if (entManager.TryGetComponent<MapLightComponent>(mapUid, out var mapLight))
            {
                Color currentActiveColor = mapLight.AmbientLightColor;

                CurrentLightHexLabel.Text = Loc.GetString("rnmc-light-current-hex", ("hex", currentActiveColor.ToHex()));
                CurrentLightColorBanner.PanelOverride = new StyleBoxFlat { BackgroundColor = currentActiveColor };
            }
        }
    }
}
