- type: job
  parent: CMJobSquadBase
  id: CMSmartGunOperatorPVE
  name: cm-job-name-smart-gun-operator
  description: cm-job-description-smart-gun-operator
  playTimeTracker: CMJobSmartGunOperatorPVE
  ranks:
    RMCRankSergeant:
    - !type:RoleTimeRequirement
      role: CMJobSmartGunOperatorPVE
      time: 252000 # 70 hours
    RMCRankCorporal:
    - !type:RoleTimeRequirement
      role: CMJobSmartGunOperatorPVE
      time: 36000 # 10 hours
    RMCRankLanceCorporal: []
  startingGear: CMGearSmartGunOperator
  dummyStartingGear: CMGearSmartGunOperatorEquipped
  icon: "CMJobIconSmartGunOperator"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  accessGroups:
  - SmartGunOperator
  overwatchSortPriority: -3
  overwatchShowName: true
  overwatchRoleName: Smart Gun Operator
  roleWeight: 1
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFirearms: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillConstruction: 2
        RMCSkillSpecialistWeapons: 7
        RMCSkillFireman: 1
        RMCSkillJtac: 1
        RMCSkillSmartGun: 1
    - type: SquadArmorWearer
    - type: JobPrefix
      prefix: cm-job-prefix-gun-operator
    - type: TacticalMapIcon
      icon:
        sprite: _RMC14/Interface/map_blips.rsi
        state: smartgunner

- type: playTimeTracker
  id: CMJobSmartGunOperatorPVE
  isHumanoid: true

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSGOSunRiders
  name: sun riders smart gun operator spawn point
  components:
  - type: SpawnPoint
    job_id: CMSmartGunOperatorPVE
  - type: Sprite
    state: marine_spawn
